[package]
name = "jusm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
logos = "0.15.1"
object = { version = "0.37.3", features = ["write"] }
thiserror = "2.0.16"
colored = "3.0.0"
